#pragma once
#define log_v(...) do {} while (0)
#define log_d(...) do {} while (0)
#define log_i(...) do {} while (0)
#define log_w(...) do {} while (0)
#define log_e(...) do {} while (0)
#define log_n(...) do {} while (0)
#define ESP_LOGE(tag, ...) do {} while (0)
#define ESP_LOGW(tag, ...) do {} while (0)
#define ESP_LOGI(tag, ...) do {} while (0)
#define ESP_LOGD(tag, ...) do {} while (0)
